version: '3'

services:
  text-gen-ts-server:
    container_name: text-gen-ts-server
    image: text-gen-ts:${IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: dockerfile.ts
    environment:
      MODEL_NAME: llama2-7b-chat
    ports:
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ./model_store:/home/model-server/model_store
      - ./config:/home/model-server/config
    networks:
      - text-gen
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  text-gen-api-server:
    container_name: text-gen-api-server
    image: text-gen-api:${IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "8087:8087"
    volumes:
      - ./fastapi_app.py:/app/fastapi_app.py
    networks:
      - text-gen

networks:
  text-gen:
